// Build one self-contained stylesheet per variant: src/palettes/<id>.css + src/base.css
// → themes/inkwell-<id>.css, and register every variant (light + dark) in package.json.
//
// Logseq loads exactly one stylesheet per plugin theme, and custom.css cannot @import,
// so each variant must ship as a single file.
//
//   node build.mjs          write themes/ and package.json
//   (tests import the functions below to check the committed files are up to date)

import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const ROOT = path.dirname(fileURLToPath(import.meta.url))
const PALETTES = path.join(ROOT, 'src', 'palettes')

export const themePath = (id) => `themes/inkwell-${id}.css`

const meta = (css, key) => {
  const m = new RegExp(`@${key}\\s+(.+)`).exec(css)
  if (!m) throw new Error(`palette is missing @${key}`)
  return m[1].trim()
}

/** [{id, name, description}] sorted by id; slate first so it is the default listing. */
export async function variants() {
  const files = (await readdir(PALETTES)).filter((f) => f.endsWith('.css'))
  const list = await Promise.all(files.map(async (f) => {
    const css = await readFile(path.join(PALETTES, f), 'utf8')
    return { id: path.basename(f, '.css'), name: meta(css, 'variant'), description: meta(css, 'description') }
  }))
  return list.sort((a, b) => (a.id === 'slate' ? -1 : b.id === 'slate' ? 1 : a.id.localeCompare(b.id)))
}

export async function buildVariant(id) {
  const { name, description } = (await variants()).find((v) => v.id === id)
  const palette = await readFile(path.join(PALETTES, `${id}.css`), 'utf8')
  const base = await readFile(path.join(ROOT, 'src', 'base.css'), 'utf8')
  const pkg = JSON.parse(await readFile(path.join(ROOT, 'package.json'), 'utf8'))
  const header = `/* ==========================================================================
   Inkwell ${name} v${pkg.version} — a Logseq DB theme
   ${description}. Light and dark follow Logseq's own theme switch.
   Install as a plugin theme (Inkwell ${name} Light / Dark), or paste this whole file into
   Settings › General › Custom theme › Edit custom.css.
   Verified against Logseq master 9c18a5432b and live on Logseq 2.0.1 (web + desktop), 2026-09-29.
   GENERATED by build.mjs from src/palettes/${id}.css + src/base.css — do not edit here.
   ========================================================================== */

`
  return header + palette.trimEnd() + '\n\n' + base.trimEnd() + '\n'
}

export async function themeEntries() {
  return (await variants()).flatMap(({ id, name, description }) =>
    ['light', 'dark'].map((mode) => ({
      name: `Inkwell ${name} ${mode === 'light' ? 'Light' : 'Dark'}`,
      url: `./${themePath(id)}`,
      description: `${description} (${mode})`,
      mode,
    })))
}

async function main() {
  await mkdir(path.join(ROOT, 'themes'), { recursive: true })
  for (const { id } of await variants()) {
    await writeFile(path.join(ROOT, themePath(id)), await buildVariant(id))
    console.log(`wrote ${themePath(id)}`)
  }
  const pkgPath = path.join(ROOT, 'package.json')
  const pkg = JSON.parse(await readFile(pkgPath, 'utf8'))
  pkg.logseq.themes = await themeEntries()
  await writeFile(pkgPath, JSON.stringify(pkg, null, 2) + '\n')
  console.log(`registered ${pkg.logseq.themes.length} themes in package.json`)
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await main()
